### ISSUE TITLE
Site still functional?

### ISSUE THREAD

**Issue by turboprops** [joshuawalcher/writtenkitten#14]
Hey - I've visited writtenkitten.co using both safari and chrome - neither are delivering images. Maybe flickr made an API change?

FYI: WriteOrDie also seems to be broken. (The author mentioned having anxiety issues and hasn't updated the site since early 2017.)

Best,

  Michael

**Comment by joshuawalcher** [comment]
Hey! Thanks for the report. Here is a shorter activation version of the program:
http://writtenkitten.co/forkids/
and it is working in Chrome. I'm testing other browsers now. I am also testing the regular site.

**Comment by joshuawalcher** [comment]
Ah, I think I discovered the issue. You were probably using a plugin that forced HTTPS if available. I have updated the core code for the website to fix an image sourcing bug when https is used. Thanks for the report!

**Comment by turboprops** [comment]
Hi Joshua,

Yeah, I just noticed that Chrome flags http://writtenkitten.net as a site with security issues. Sorry! I think they (Google) started doing that with all http sites in release 68, earlier this year.

Thanks for catching the issue and updating! 

Hm… I don’t know what your work progress is, but I shifted over to the https: version of writtenkitten in Chrome, dumped my browser cache, and I’m noticing a couple things. First, I’m still not getting kittens in Chrome. (Version 71.0.3578.98) Also, the title font has changed and the current word count isn’t updating. 

I hope this helps!

Best regards,

  Michael

**Comment by joshuawalcher** [comment]
If you have stored data, you may not see the word count until you interact with the text box (i.e. clicking a space bar or typing a letter). But I am seeing word count in both HTTPS and HTTP with Chrome 71.0.3578.98.

Maybe the cache didn't catch the JS change? Try holding down the shift key on your keyboard and clicking the refresh icon. That should get your browser to hard refresh the JS files.

**Comment by turboprops** [comment]
Hm… I tried dumping the Chrome cache using your instructions and the site still didn’t seem to work. (Still no kittens, font change, and current word count not updating.)

So, I also cleared my cache on Safari and tried the site; I see the exact same issues I mentioned being seen in Chrome. (Above)

I’m running a 2016 MacBook Pro. (10.14.2 build)

The screenshot I included with this message is of safari. 

And, I just tried it on Chrome on my iPhone for the first time… same behavior there.

Do you have a alternative machine you could try?

Best,

  Michael
