### ISSUE TITLE
Host via GitHub Pages?

### ISSUE THREAD

**Issue by SeanKilleen** [joshuawalcher/writtenkitten#2]
The site is just a few files that sit in a root directory. GitHub Pages is actually great at serving those.

Advantages:

* It's fast
* It's free
* It's reliable (GitHub themselves run off the same infrastructure)
* Deployment is just a merge into a `gh-pages` branch
* Can still work with custom DNS names.

It's really easy to set up, and I think it'd be a neat way to make this work. Let me know if you're interested.

**Comment by joshuawalcher** [comment]
I'd totally agree except that I'm adding dynamic features that require client-side code and that won't work with Github Pages.
