### ISSUE TITLE
No kitten displayed with "Uncaught ReferenceError: sharefb is not defined" in console

### ISSUE THREAD

**Issue by Taelkir** [joshuawalcher/writtenkitten#20]
Setting the word counter to display a new picture every 100 words and typing 100 words doesn't display a picture. The console displays a "Uncaught ReferenceError: sharefb is not defined" error at `WrittenKitten.js:103:4`. First noticed in Firefox, also tested in Chrome and Edge.

**Comment by joshuawalcher** [comment]
Thanks!

**Comment by joshuawalcher** [comment]
Kitten still not displaying. This is because Flickr updated their API to require an API key and maybe some other things. Working on that now.

**Comment by joshuawalcher** [comment]
Fixed. Skud's old API key finally expired. LOL.
