### ISSUE TITLE
Written kitten for kids not displaying images

### ISSUE THREAD

**Issue by Claude-at-Instaclustr** [joshuawalcher/writtenkitten#24]
The system now counts the words correctly #23 but images are not displayed after the number of words has been reached.  I attemped with every 5 and 10 words selected and I added 145 words to the text.  No picture. :(

**Comment by Claude-at-Instaclustr** [comment]
I think that at line 77 of writtenkitten.js where it reads:

```
                          fetch_next_kitten();
			}
```
The fetch_next_kitten() call should be outside the curly brace.  

I have also notices that the UI does not update when the page is reloaded.  My display says every 5 words but the code was still looking for every 10 words.

**Comment by joshuawalcher** [comment]
This ended up being more complicated than initially expected, but is now resolved. There was a license key issue as well as a need to re-architect some of the code. Sorry for the inconvenience!

**Comment by Claude-at-Instaclustr** [comment]
thanks for the fix.  My grandkids will love this.
