### ISSUE TITLE
request for photos to include actual kittens and cats only

### ISSUE THREAD

**Issue by ellielinc** [joshuawalcher/writtenkitten#25]
very convenient to see students' word count with bonus of cute cat pics, but this is not the content I hope to see :[ 

![image](https://user-images.githubusercontent.com/28547282/158667424-761b620b-5f8e-44b9-b79d-5ed1dfac75b6.png)

**Comment by joshuawalcher** [comment]
Oof, don't like that! I periodically have to block content from specific users that use "cute kitten" in their tags or their username. I'll get this one blocked. Sorry for the trouble!

**Comment by ellielinc** [comment]
thanks for the quick response! the internet is a vast and strange place..

**Comment by joshuawalcher** [comment]
I have added the block of that user.
