### ISSUE TITLE
Move to MVVM-style?

### ISSUE THREAD

**Issue by SeanKilleen** [joshuawalcher/writtenkitten#3]
I'm a big fan of MVVM-style JS over jQuery's more declarative syntax. 

I think we could do the following and polish it up really nicely:
- Add a suite of tests that aren't implemented yet (to describe the current functionality)
- Build the site in an MVVM style, using fakes for the Flickr API calls
  - Knockout would probably be easiest for this. Well-known, old browser support, easy, etc. etc. 
- Once all the tests are passing, change the HTML to use Knockout bindings rather than jQuery declarations
- Test the web page
- If it looks like it works as expected, and passes all tests, remove all the jQuery script
- Test again
- If it looks good, deploy.

Thoughts?

**Comment by joshuawalcher** [comment]
No opinion - but I'm always happy to look at what you've got when you think it's ready and make a decision then.
