### ISSUE TITLE
Separate in-line CSS/JS into their own files

### ISSUE THREAD

**Issue by SeanKilleen** [joshuawalcher/writtenkitten#4]
While there is a `styles` directory and a `local.js` file, it doesn't appear that the `index.html` file actually refers to them.

**Comment by SeanKilleen** [comment]
@joshuawalcher it looks like this may been in-progress / have been in progress at the time you opened the repo.

I'm thinking it would make sense to re-extract things, write over the existing CSS and JS files with the original that's being used in the web page now, and then update the web page to refer to the files.

If you're okay with that, let me know -- shouldn't take long at all to do a PR for it.

**Comment by joshuawalcher** [comment]
Yup, I am moving all the inline CSS to a file in the css directory and am currently testing the CSS for tabs. I'm not opposed to you finishing the inline -> single-file work while I work on tabs and such.
